### ISSUE TITLE
Furnaces error

### ISSUE THREAD

**Issue by hexagon02** [ItsSchatten/PortableCraftingInvs#30]
Hello,
I'm using PCI on a bungeecord server (using same mysql on different survival servers).
When I try to use the virtual furnace, this error is sent in console and the furnace is not working.

```
[17:27:59 ERROR]: Could not pass event InventoryClickEvent to PortableCraftingInvs v1.6.10
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "this.fuelItem" is null
        at com.itsschatten.portablecrafting.libs.recipe.FurnaceFuel.getFuel(FurnaceFuel.java:167) ~[PortableCraftingInvs-1.6.10.jar:?]
        at com.itsschatten.portablecrafting.libs.FurnaceListener.isNotVanillaFuel(FurnaceListener.java:139) ~[PortableCraftingInvs-1.6.10.jar:?]
        at com.itsschatten.portablecrafting.libs.FurnaceListener.onInventoryClick(FurnaceListener.java:89) ~[PortableCraftingInvs-1.6.10.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1394]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1394]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1394]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2886) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1394]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[17:28:03 ERROR]: Could not pass event InventoryClickEvent to PortableCraftingInvs v1.6.10
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "this.fuelItem" is null
        at com.itsschatten.portablecrafting.libs.recipe.FurnaceFuel.getFuel(FurnaceFuel.java:167) ~[PortableCraftingInvs-1.6.10.jar:?]
        at com.itsschatten.portablecrafting.libs.FurnaceListener.isNotVanillaFuel(FurnaceListener.java:139) ~[PortableCraftingInvs-1.6.10.jar:?]
        at com.itsschatten.portablecrafting.libs.FurnaceListener.onInventoryClick(FurnaceListener.java:89) ~[PortableCraftingInvs-1.6.10.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1394]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1394]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1394]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2886) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293) ~[patched_1.17.1.jar:git-Purpur-1394]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1394]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

Any idea of what it may be caused by?
Thank you very much!

**Comment by ItsSchatten** [comment]
This is an error on my side. The way the feature was designed was to simplify lookups for a player's furnace and to be much more responsive, it wasn't ever meant to be used as a cross server solution.

Because of the way that the current furnace system is built it will likely require a rewrite in order to make this cross server, I'll mark this issue as an Enhancement and begin working on it.

**Comment by hexagon02** [comment]
Thank you, so are you suggesting me to disable furnace's feature for now?

**Comment by ItsSchatten** [comment]
if you wish to have a cross-server furnaces and brewing stands, yes. You could use the file system version for now if you would like, I will likely attempt to transfer over any file data for a furnace into the sql database. (This will likely be sort of tricky, but I would suggest just disabling them for now.)

**Comment by hexagon02** [comment]
Ok, thank you for the fast answer! Thank you for your job
