### ISSUE TITLE
Cant get plugin to load

### ISSUE THREAD

**Issue by AcesGamingUK** [ItsSchatten/PortableCraftingInvs#41]
Server: Paper(445) 1.19.3-R0.1-SNAPSHOT
Plugin: 1.7.6

<details>
  <summary>Plugin Error</summary>

```JS
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] Enabling PortableCraftingInvs v1.7.6
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] 
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] +---------------------------------------------------+ 
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] 
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs]  _____   _____ _____ 
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] |  __ \ / ____|_   _|
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] | |__) | |      | |  
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] |  ___/| |      | |  
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] | |    | |____ _| |_ 
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] |_|     \_____|_____|
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] 
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] Developed by ItsSchatten
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] Version 1.7.6
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] Using Minecraft version v1_19_R2
[03:28:21] [Server thread/ERROR]: Error occurred while enabling PortableCraftingInvs v1.7.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.itsschatten.portablecrafting.libs.RecipeManager.registerRecipes(RecipeManager.java:86) ~[PortableCraftingInvs.jar:?]
	at com.itsschatten.portablecrafting.libs.RecipeManager.<init>(RecipeManager.java:35) ~[PortableCraftingInvs.jar:?]
	at com.itsschatten.portablecrafting.libs.VirtualFurnaceAPI.<init>(VirtualFurnaceAPI.java:84) ~[PortableCraftingInvs.jar:?]
	at com.itsschatten.portablecrafting.FakeContainers_v1_19_R2.<init>(FakeContainers_v1_19_R2.java:50) ~[PortableCraftingInvs.jar:?]
	at com.itsschatten.portablecrafting.PortableCraftingInvsPlugin.registerFakeContainers(PortableCraftingInvsPlugin.java:269) ~[PortableCraftingInvs.jar:?]
	at com.itsschatten.portablecrafting.PortableCraftingInvsPlugin.onEnable(PortableCraftingInvsPlugin.java:148) ~[PortableCraftingInvs.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-445]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-445]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-445]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.RecipeChoice.getItemStack()" because "this.ingredient" is null
	at org.bukkit.inventory.CookingRecipe.getInput(CookingRecipe.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at com.itsschatten.portablecrafting.libs.recipe.FurnaceRecipe.lambda$static$1(FurnaceRecipe.java:56) ~[PortableCraftingInvs.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at com.itsschatten.portablecrafting.libs.recipe.FurnaceRecipe.<clinit>(FurnaceRecipe.java:36) ~[PortableCraftingInvs.jar:?]
	... 18 more
[03:28:21] [Server thread/INFO]: [PortableCraftingInvs] Disabling PortableCraftingInvs v1.7.6
[03:28:21] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling PortableCraftingInvs v1.7.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.itsschatten.portablecrafting.libs.task.FurnaceTick.cancel()" because "this.furnaceTick" is null
	at com.itsschatten.portablecrafting.libs.VirtualFurnaceAPI.disableAPI(VirtualFurnaceAPI.java:125) ~[PortableCraftingInvs.jar:?]
	at com.itsschatten.portablecrafting.PortableCraftingInvsPlugin.onDisable(PortableCraftingInvsPlugin.java:288) ~[PortableCraftingInvs.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[paper-1.19.3.jar:git-Paper-445]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.19.3.jar:git-Paper-445]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:196) ~[paper-1.19.3.jar:git-Paper-445]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-445]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-445]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-445]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

  </details>

**Comment by ItsSchatten** [comment]
Do you happen to have any plugins that alter the recipies on your server?

**Comment by AcesGamingUK** [comment]
I have [CMI](https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/) and [CustomCrafting](https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-16-1-19-free.55883/)

**Comment by ItsSchatten** [comment]
Whoops, sorry for such a late response. 

Thanks! I'll dig around a little and see if I can resolve the issue you're experiencing.

**Comment by ItsSchatten** [comment]
The plugin should load for you know. If it doesn't, please update me with any new errors you receive.

**Comment by AcesGamingUK** [comment]
seems to load now with the following error
<details>
  <summary>ERROR</summary>

```JS
ERROR
?7[?bVirtual?3Furnace?7]: Failed to load a furnace recipeiron_nugget_from_smelting! Cannot invoke "org.bukkit.inventory.RecipeChoice.getItemStack()" because "this.ingredient" is null
?7[?bVirtual?3Furnace?7]: Failed to load a furnace recipeiron_nugget_from_blasting! Cannot invoke "org.bukkit.inventory.RecipeChoice.getItemStack()" because "this.ingredient" is null
```

  </details>

**Comment by ItsSchatten** [comment]
Sorry for getting back so late, forgot about this issue.
Uhhhm, if this is still an issues does the recipe mentioned (iron_nugget_from_smelting/blasting) work in a normal furnace/blast furnace? If it does it may actually be an issue with how the furnace API I use loads in recipes, though I can't seem to find any issues with it.

I also couldn't seem to replicate it with my minimal amount of testing, if you are still seeing the same error I'll redo some testing to see if I can get it figured out.

**Comment by AcesGamingUK** [comment]
so i did some poking about "as i totally forgot about this too"
the furnaces.yml is empty on install,
however i added
`furnace: {}` to the file and the error went away, (i looked in the brewing yml and basically copied it over)
