### ISSUE TITLE
Furnace/Smoker/Blast Not Working

### ISSUE THREAD

**Issue by AabegR** [ItsSchatten/PortableCraftingInvs#8]
Um Hi,
I really liked your plugin but I'm having issues with the Furnace/Smoker/Blast. Everything else is working and there aren't any errors on the Server Console. 1.16 Server!
Some Assitance would be Greatly Appreciated! :)

**Comment by ItsSchatten** [comment]
Hi AabegR,

Could you please explain your issue more in-depth? Not working could mean a multiple of things. Also, if you could be a bit more specific with your version, 1.16-1.16.1 are different compared to 1.16.2-1.16.3.

Do the furnaces just not work? As in nothing is ever smelted when you put things in the furnace?

**Comment by AabegR** [comment]
> Hi AabegR,
> 
> Could you please explain your issue more in-depth? Not working could mean a multiple of things. Also, if you could be a bit more specific with your version, 1.16-1.16.1 are different compared to 1.16.2-1.16.3.
> 
> Do the furnaces just not work? As in nothing is ever smelted when you put things in the furnace?

If I place any smeltable item it wouldn't do anything and if I just leave things there and exit the things I placed in it would disappear... My server is in 1.16.1

**Comment by ItsSchatten** [comment]
Whoops I forgot one more piece of information; which version of the plugin are you using?

**Comment by AabegR** [comment]
> Whoops I forgot one more piece of information; which version of the plugin are you using?

Its 1.3.1 and also here is the error that is now coming up after not being able to access the furnace anymore (crafting is working)

**Comment by AabegR** [comment]
nonon i didnt mean to close it
Im using 1.3.1

**Comment by AabegR** [comment]
Now this is popping up on my console after not being able to access the furnace, blaster and smoker


org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2191) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
	at com.cloudcraftgaming.spawnjoin.listeners.InventoryListener.onInventoryClick(InventoryListener.java:46) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-0287a20-7560f5f]
	... 18 more

**Comment by AabegR** [comment]
Ummm also I just deleted the Config file created by the Jar and.... it's saying that I opened the furnace whenever I run the command but the popup is not shown....
hmmm 🤔

**Comment by ItsSchatten** [comment]
I believe I may have located the issue. I will update you if I confirm it is in-fact an issue. My deepest apologies that you are experiencing these issues.

On another note: I do not think that the error provided persists to my plugin, it appears to belong to a plugin called spawnjoin.

**Comment by AabegR** [comment]
> I believe I may have located the issue. I will update you if I confirm it is in-fact an issue. My deepest apologies that you are experiencing these issues.
> 
> On another note: I do not think that the error provided persists to my plugin, it appears to belong to a plugin called spawnjoin.

Take your time don't rush it! 😊
About the SpawnJoin plugin... it's pretty much like that when I or someone clicks something on a gui.
I will try tmrw morning to see if it's related to SpawnJoin tho... it's 10:32pm gtg sleep 😧
Enjoy your time!

**Comment by ItsSchatten** [comment]
GOOD NEWS! It was an incredibly easy fix that I really don't know how I missed. I will release an update to Spigot, thank you so much for reporting the issue!

To explain: I failed to realize that I was attempting to access values from the settings.yml before even registering said values, because of how booleans work in Java it all worked besides the furnace logic, this has been fixed and I will take extra care in the future to double check my work before releasing an update. 

**If you find the issue still persists after the update, please reopen this issue.**

**Comment by AabegR** [comment]
Oh my gawd u did magik well done 😊 I'm proud!
Thank you for the quick fix and support!
